# Generated by Django 6.0.3 on 2026-03-21 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["city"]},
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["quantity"]},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["placed_at"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["unite_price"]},
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"ordering": ["discount"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="promotions",
            field=models.ManyToManyField(blank=True, to="store.promotion"),
        ),
    ]
