# Generated by Django 6.0.3 on 2026-03-25 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_cartitem_unique_together_cartitem_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="order",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
