# Generated by Django 6.0.3 on 2026-03-29 11:51

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_cartitem_product_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costumer",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="costumer",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[store.validators.validate_file_size],
            ),
        ),
    ]
