# Generated by Django 6.0.3 on 2026-04-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_costumer_birth_date_alter_costumer_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
    ]
