# Generated by Django 6.0.3 on 2026-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("R", "Processing"),
                    ("S", "Shipped"),
                    ("D", "Delivered"),
                    ("C", "Cancelled"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CD", "Card"), ("CA", "Cash")],
                max_length=2,
                null=True,
            ),
        ),
    ]
