# Generated by Django 6.0.3 on 2026-03-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["label"]},
        ),
    ]
